name: Notify on Client Creation

on:
  workflow_dispatch:
    inputs:
      client_name:
        description: 'Nombre del cliente creado'
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        run: echo "Nuevo cliente creado: ${{ github.event.inputs.client_name }}"